blank_issues_enabled: false
contact_links:
    - name: 💬 Discord Server
      url: https://discord.gg/E8M5gPC
      about: Please ask and discuss questions here.
    - name: 📃 Documentation
      url: https://github.com/FVANtom/SpiritsOfTerra-Open#get-started
      about: Please refer to it as our main documentation.
