name: End to End Testing

on: [push, pull_request]

jobs:
    test:
        name: Run tests

        runs-on: ubuntu-latest

        steps:
            - name: Checkout on ${{ runner.os }}
              uses: actions/checkout@v3

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.5.0
                  cache: 'yarn'

            - name: Install stubs
              run: chmod +x ./installSotStubs.sh && ./installSotStubs.sh
              shell: bash

            - name: Run Cypress
              uses: cypress-io/github-action@v4
              with:
                  command: yarn workspace @kaetram/e2e test:run

            - name: Notify discord
              if: always()
              uses: sarisia/actions-status-discord@v1
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  nodetail: true
                  nofail: false
                  title: New code was added to the public SOT repository
                  description: |
                      Test status
                      `${{ job.status }}`

                      Details
                      Click [here](https://github.com/FVANtom/SpiritsOfTerra-Open/actions/workflows/e2e.yml) to go to the github workflow logs.
